<?php

namespace ShiftBundle\Repository;
use Doctrine\ORM\EntityRepository;
use ShiftBundle\Entity\Shift;

/**
 * ShiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiftRepository extends EntityRepository
{
    /**
     * @see EntityManagerInterface::persist
     * @param Shift $object
     */
    public function persist(Shift $object) {
        $this->getEntityManager()->persist($object);
    }

    /**
     * @see EntityManagerInterface::remove
     * @param Shift $object
     */
    public function remove(Shift $object) {
        $this->getEntityManager()->remove($object);
    }

    /**
     * @see EntityManagerInterface::flush
     * @param Shift $object
     */
    public function flush(Shift $object = null) {
        $this->getEntityManager()->flush($object);
    }
}
