AppBundle:
    resource: "@AppBundle/Controller/"
    type:     annotation

FOSUserBundle:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc