ShiftBundle:
    resource: "@ShiftBundle/Controller/"
    type:     annotation
    prefix:   /api
    defaults:
        _format: json

AppBundle:
    resource: "@AppBundle/Controller/"
    type:     annotation

FOSUserBundle:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

FOSUserBundleGroups:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /groups

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc