FOS\Message\Model\ConversationPerson:
    relations:
        -   rel: conversation
            embedded:
                content: expr(object.getConversation())
            exclusion:
                groups:
                    - conversation_list
        -   rel: person
            embedded:
                content: expr(object.getPerson())
            exclusion:
                groups:
                    - conversation_list