FOS\Message\Model\Conversation:
    relations:
        -   rel: self
            href: "expr(object.getId())"
            exclusion:
                groups:
                    - conversation_list
                    - conversation_detail
        -   rel: users
            href: xyz
            exclusion:
                groups:
                    - conversation_list